name: flutter_news_app
description: Flutter News App with NewsApi
version: 2.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # A powerful Http client for Dart, which supports interceptors, FormData, Request Cancellation,
  # File Downloading, Timeout etc.
  dio: ^3.0.9

  # Flutter widgets that make it easy to implement the BLoC design pattern.
  flutter_bloc: ^3.2.0

  # Package provides internalization and localization facilities, including message translation,
  # plurals and genders, date/number formatting and parsing, and bidirectional text.
  intl: ^0.16.1

  # Flutter plugin for launching a URL in the mobile platform. Supports iOS and Android.
  url_launcher: ^5.4.2

  # Flutter library to load and cache network images. Can also be used with placeholder and
  # error widgets.
  cached_network_image: ^2.1.0+1

  # Simple direct Service Locator that allows to decouple the interface from a concrete
  # implementation and to access the concrete implementation from everywhere in your App
  get_it: ^4.0.1

  # Functional Programming in Dart. Purify your Dart code using efficient immutable data structures,
  # monads, lenses and other FP tools.
  dartz: ^0.8.9

  # An abstract class that helps to implement equality without needing to explicitly
  # override == and hashCode
  equatable: ^1.1.1

  # A pure Dart library that checks for internet by opening a socket to a list of specified
  # addresses, each with individual port and timeout.
  data_connection_checker: ^0.3.4

  # A Flutter plugin for adapting screen and font size.
  flutter_screenutil: ^1.1.0

  # How to get the most value from Dart static analysis.
  pedantic: ^1.8.0+1

  # Flutter plugin providing detailed information about the device (make, model, etc), and
  # Android or OS version the app is running on.
  device_info: ^0.4.2+1

  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable
  # Vector Graphics 1.1 files.
  flutter_svg: ^0.17.4

  # Lightweight and blazing fast key-value database written in pure Dart.
  hive: ^1.4.1+1

  # Extension for Hive. Make it easier to use Hive in Flutter apps.
  hive_flutter: ^0.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Tools to write binaries that run builders.
  build_runner: ^1.8.1

  # A mock framework inspired by Mockito.
  mockito: ^4.1.1

  # A testing library which makes it easy to test blocs.
  bloc_test: ^4.0.0

  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^3.3.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
